version: '3.4'

services:
  db:
    environment:
      - POSTGRES_USER=my-user
      - POSTGRES_PASSWORD=my-password
      - POSTGRES_DB=RandomApp
    ports:
      - "5433:5432"
  web-api:
    environment:
      - Frontend:Url=http://0.0.0.0
    ports:
      - "5000:80"
  angular-app:
    environment:
      - webapi=http://0.0.0.0:5000