version: '3.4'

services:
  db:
    image: random-db
    build:
      context: .
      dockerfile: ./src/db/Dockerfile
  web-api:
    image: random-web-api
    build: 
      context: .
      dockerfile: ./src/api/RandomWebApi/Dockerfile
    environment:
      - Database:Server=db
  angular-app:
    image: random-angular-app
    build: ./src/RandomAngularApp
    ports:
      - "80:80"